apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: aichichangnandos/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        # when skaffold sees a js/css/html file changes, it will take it anf through it to the contianer
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: aichichangnandos/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    - image: aichichangnandos/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectl:
    # we list out all the config files that we want skaffold to manage for us
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml